name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Get Poetry version
        run: poetry --version
      - name: Check pyproject.toml validity
        run: |
          poetry lock
          poetry check --no-interaction
      - name: Setup package
        run: poetry install --no-interaction
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - name: Publish package
        run: poetry publish --build
