name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSLO https://github.com/python-poetry/poetry/raw/020fb336e6da11d3a9909f30bd908437a69f13b3/get-poetry.py && python get-poetry.py --uninstall && python get-poetry.py    
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Get Poetry version
        run: poetry --version
      - name: Check pyproject.toml validity
        run: poetry check --no-interaction
      - name: Setup package
        run: poetry install --no-interaction
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - name: Publish package
        run: poetry publish --build
